spring:
  application:
    name: index-codes-service
  zipkin:
    base-url: http://localhost:9411
  redis:
    port: 6379
    database: 2
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
