eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
spring:
  application:
    name: third-part-index-data-service
  redis:
    port: 6379
    database: 2
    host: 127.0.0.1